CREATE TABLE Lieu (id INTEGER PRIMARY KEY, nom VARCHAR(30), adr VARCHAR(50), capacite INTEGER );

INSERT INTO Lieu VALUES (1,'SALLE DU PANIER FLEURI','Rue de Boneville',450) ;
INSERT INTO Lieu VALUES (2,'LE CABARET','MAIRIE ANNEXE DE PARAME, Place Georges COUDRAY',250) ;
INSERT INTO Lieu VALUES (3,'LE PARC DES CHENES','14 rue des chênes',2000) ;
INSERT INTO Lieu VALUES (4,'LE VILLAGE','Ecole LEGATELOIS, 25 rue Général de Catselnau',500) ;
